import { Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/fragments/header/Header";
import Layouts from "@/components/layouts";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Layouts>
          <Header />
          {children}
        </Layouts>
      </body>
    </html>
  );
}
